modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/sudolev/minecraft-magic-feather/issues"

[[mods]]
modId="magicfeather"
version="0.01"
displayName="Magic Feather: Replumed"
displayURL="https://www.curseforge.com/minecraft/mc-mods/magic-feather"
logoFile="logo.png"
credits="RWTema, Fuzss"
authors="Ephys, EizhFox, sudolev"
description='''
The Magic Feather item is an alternative take on the Angel Ring from Extra Utilities.

It balances creative flight by making it only available around Beacons, thus forcing the player
to use alternative methods of travel when exploring.

Magic Feather: Replumed is a port of Magic Feather for versions 1.19+
'''
[[dependencies.magicfeather]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.magicfeather]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.magicfeather]]
    modId="curios"
    mandatory=false
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
