modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/sudolev/minecraft-magic-feather/issues"

[[mods]]
modId="magicfeather"
version="1.0.0"
displayName="Magic Feather: Replumed"
displayURL="https://www.curseforge.com/minecraft/mc-mods/magic-feather"
logoFile="logo.png"
credits="RWTema, Fuzss"
authors="sudolev, Ephys, EizhFox, Leclowndu93150"
description='''
Magic Feather: Replumed is a continuation of the Magic Feather mod for versions 1.19+.

The Magic Feather item is an alternative take on the Angel Ring from Extra Utilities.

It balances creative flight by making it only available around Beacons, thus forcing the player
to use alternative methods of travel when exploring.
'''
[[dependencies.magicfeather]]
    modId="neoforge"
    mandatory=true
    versionRange="[21,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.magicfeather]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.magicfeather]]
    modId="curios"
    mandatory=false
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
